### ISSUE TITLE
command_move fails at one particular position

### ISSUE THREAD

**Issue by knzivid** [EPC-MSU/libximc#3]
I am using ximc 2.12.5 on linux, amd64. Using `command_move` does not work for some values. For instance,

- position = 22430 - result_ok
- position = 25000 - result_ok
- position = 25068 - result_error
- position = 27666 - result_ok

Does the `position` argument to `command_move` have any constraints? I think I may have misunderstood what `position` means.

**Comment by Zapunidi** [comment]
There are no constraints, except the maximum and minimum values for integer type in result_t XIMC_API | command_move (device_t id, **int** Position, **int** uPosition). Values of 20000-30000 certainly do not exceed them.
You most certainly have issues not with the library code, but with the system as a whole (encoders, electromagnetic interference, linux subsystems etc). Best open a ticket in 8SMC5-USB support system: https://xisupport.com
