### ISSUE TITLE
Building from source on ubuntu 16.04

### ISSUE THREAD

**Issue by knzivid** [EPC-MSU/libximc#4]
Can I build libximc from source as a static library on ubuntu 16.04? 

https://github.com/EPC-MSU/libximc/blob/15c9b4380ae6bc7878d7bbc79b16862212866d85/libximc/docs/doc-en/docmainpage.c#L87

says it supports debian squeeze 7 for amd64-linux.

**Comment by Zapunidi** [comment]
You can't build any dynamic lib as static lib when it call another dynamic lib itself. Not with uncommon and dark programming rituals. libximc uses dynamic xiwrapper lib and bindy lib. So general answer to your question is no.

**Comment by knzivid** [comment]
> when it call another dynamic lib itself

Do you mean libximc.so links to xiwrapper and bindy at link time or at runtime with `dlopen`?

**Comment by Marladon** [comment]
Libximc library binds to xiwrapper and bindy both at build time and at runtime with dlopen. Dependent libraries are written in code, after all, you still won't be able to build the libximc library as a static one

**Comment by knzivid** [comment]
I built libximc 2.12.1 with static bindy, static ximcwrapper and static cryptopp. You mentioned libximc binds to xiwrapper and bindy at runtime with dlopen. However, I did not see any explicit calls to libdl in libximc.

If I build all the dependencies of libximc as static libraries, why shouldn't it work? The only changes I made to the ci build script was to mark the cmake target as STATIC and use BUILD_SHARED_LIBS=OFF with cmake. We also verified this build at runtime with 8SMC5-USB.

Do you see any problems with us doing this? The reason we do it is that static libximc makes internal distribution and deployment easier for us.

**Comment by theirix** [comment]
Hello, @knzivid .

It is totally possible to use a static linkage to libximc. Dynamic loading via `dlopen` is not used so it should be safe. However, if you are using static linking to libximc, you need to specify all transitive dependencies at linker invocation and take care to collect all transitive deps like cryptopp. Please take a note that several system libraries like `libstdc++` or `libc++` must be linked statically too, not all platforms support that.

For example, on Linux:

```
cc testapp_C.c -I/tmp/libximc-inst/include \
  -L/tmp/libximc-inst/lib -L`pwd`/../../deps/xiwrapper/ -L`pwd`/../../deps/bindy/vendor/cryptopp/ \
  -lximc -lxiwrapper  -lbindy -llibstdc++ -lcryptopp -lm -lpthread
```
and on mac:

```
cc testapp_C.c -DNOFRAMEWORK -I/tmp/libximc-inst/include \
  -L/tmp/libximc-inst/lib -L`pwd`/../../deps/xiwrapper/ -L`pwd`/../../deps/bindy/vendor/cryptopp/ \
  -lximc -lxiwrapper  -lbindy -lstdc++ -lcryptopp -framework CoreFoundation -framework IOKit
```

We will add soon a few fixes found with static linking. Static library can be produced by `configure` call for libximc, and by cmake calls with `-DBUILD_SHARED_LIBS=OFF` for bindy and xiwrapper. Automatic script `build.sh` and packages will still include shared libraries only.

**Comment by theirix** [comment]
libximc in dev-2.13 and its deps are updated with fixes.

You should be able to build and install the library with something like (feel free to change the CI script for your needs):
```
DEPS_CMAKE_OPT="-DBUILD_SHARED_LIBS=OFF" ./build.sh libfast --with-staticdeps
```

**Comment by knzivid** [comment]
Thank you for the detailed response. We do not intend to static link to libc or libstdc++. We are building this on an old enough distro, so it is forward compatible with newer versions of libc and libstdc++.
